name: Frontend SBOM

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Generate SBOM
        run: npx @cyclonedx/cyclonedx-npm --output-file sbom.json

      - name: Scan SBOM with Grype (SARIF)
        uses: anchore/scan-action@v4
        with:
          sbom: sbom.json
          output-format: sarif
          fail-build: false
          severity-cutoff: high

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif

      - name: Fail pipeline if vulnerabilities found
        run: |
          echo "High or Critical vulnerabilities detected."
          exit 1
